// Codegen: inline every shaders/*.wgsl into src/shaders.generated.ts as a string map,
// so the runtime never fetch()es shader files. JSON.stringify handles all escaping
// (newlines, quotes), so the embedded source is byte-identical to the .wgsl on disk.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const shaderDir = join(here, '..', 'shaders')
const outFile = join(here, '..', 'src', 'shaders.generated.ts')

const files = readdirSync(shaderDir)
  .filter((f) => f.endsWith('.wgsl'))
  .sort()

let body = ''
for (const file of files) {
  const name = file.slice(0, -'.wgsl'.length)
  const code = readFileSync(join(shaderDir, file), 'utf8')
  body += `  ${JSON.stringify(name)}: ${JSON.stringify(code)},\n`
}

const out =
  '// AUTO-GENERATED by scripts/gen-shaders.ts from shaders/*.wgsl. Do not edit by hand.\n' +
  `export const SHADERS: Record<string, string> = {\n${body}}\n`

writeFileSync(outFile, out)
console.log(`gen-shaders: inlined ${files.length} shaders -> src/shaders.generated.ts`)
